### ISSUE TITLE
Video skipping not working

### ISSUE THREAD

**Issue by rusudorin** [plexinc/plex-for-kodi#310]
## Description:
Video skipping not working anymore since Kodi 18.6 update on Android TV

## Details:
- Add-on version: 0.1.7
- Kodi version: 18.6
- OS Platform: Android TV
- Hardware: Nvidia Shield Pro

**Comment by mbarbeaux** [comment]
Same here

**Comment by ruuk** [comment]
I'm going to need some more info since I'm not seeing this issue on my end.
- A detailed description of what you mean by 'Video skipping' - e.g. the skip buttons aren't working, the seek bar doesn't seek on enter (this is fixed for an upcoming release), seeking just doesn't work at all.
- The Plex server version
- Kodi logs from when this happens
- Does this happen on all media of all types?

**Comment by rusudorin** [comment]
The seek doesn't work on enter. If this is fixed in an upcoming, I'll wait until the release.

**Comment by blizz05** [comment]
Hi I see in the changelog there is a 0.1.8 version but I can't seem to update it from kodi repo. It still shows 0.1.7 as the latest version. How can I install the latest one? The seek issue is really troublesome.

**Comment by matthew10199** [comment]
Hey I'm still having this problem. I'm not having it all the time, only when it's near the end of an episode (in the last couple minutes, at the point when hitting the back button would go to the next episode loading screen at the end of a show, where it counts down to the next episode, rather than backing all the way out to the season page). At that point if I try to skip it will often skip past an episode, for instance if I am at the end of episode 3 and skip, it will play episode 5 next, also that next episode loading screen I described earlier will pop up and show episode 5.

I first noticed this problem after getting an update to v0.1.7 of the Plex for Kodi add-on. I'm not sure about the version of Kodi/Plex at the time.

Currently I am experiencing the problem with these versions:
Plex for Kodi 0.2.0 
Kodi 18.3
Plex Server 1.19.2.2702

**Comment by blizz05** [comment]
Hi @matthew10199. The issue you are mentioning is slightly different to this one. We are referring to video seeking, like rewinding or fast-forwarding when the seek bar is visible and pressing enter. That has been fixed in 0.2.0 I believe.

Another person on the plex forums has mentioned something similar to what you are experiencing:
https://forums.plex.tv/t/only-for-serious-testers-bleeding-edge-testing-releases/471733/43

Is this what you are referring to?

**Comment by matthew10199** [comment]
Hi @blizz05, yah that's exactly my problem
